name: Alpine Rootfs Build

on:
  schedule:
    - cron: '0 0 15 * *'
  workflow_dispatch:

jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build rootfs
        run: |
          git clone git://git.alpinelinux.org/aports
          cd aports/scripts
          ./mkimage.sh -s main -r -t alpine-rootfs:latest

      - name: Export rootfs as tarball
        run: |
          mkdir -p rootfs
          container_id=$(docker create alpine-rootfs:latest)
          docker export "$container_id" | tar -C rootfs -xz
          docker rm "$container_id"

      - name: Add rootfs to branch
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update rootfs"
          directory: "rootfs"
          branch: "main"
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          commit_message: "Update rootfs on ${{ github.sha }}"
