name: Build and Publish Alpine Rootfs
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Alpine Rootfs
      run: |
        docker run --rm -v $(pwd):/build -w /build alpine:latest sh -c "apk update && apk add alpine-sdk && setup-alpine -f ./setup.conf -s --profile minimal && tar czvf rootfs.tar.gz -C alpine/ ."

    - name: Upload Rootfs Tarball
      uses: actions/upload-artifact@v2
      with:
        name: rootfs
        path: rootfs.tar.gz
