name: Build and Publish Alpine Rootfs
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build . -t my-alpine-image
      - name: Create Rootfs Tarball
        run: docker run --rm my-alpine-image tar czvf /github/workspace/rootfs.tar.gz -C / .

      - name: Upload Rootfs Tarball
        uses: actions/upload-artifact@v2
        with:
          name: rootfs
          path: rootfs.tar.gz
