name: Build Alpine RootFS
on:
  schedule:
    - cron: '0 0 15 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install debootstrap and qemu-user-static
      run: |
        sudo apt-get update
        sudo apt-get install -y debootstrap qemu-user-static

    - name: Create rootfs with debootstrap
      run: |
        sudo debootstrap --variant=minbase --components=main,community alpine alpine
        sudo cp /usr/bin/qemu-arm-static alpine/usr/bin/
    
    - name: Create tar.gz archive of rootfs
      run: |
        cd alpine && tar -czvf ../rootfs.tar.gz *
    
    - name: Save rootfs.tar.gz artifact
      uses: actions/upload-artifact@v2
      with:
        name: rootfs.tar.gz
        path: rootfs.tar.gz
