name: Build Alpine RootFS
on:
  schedule:
    - cron: '0 0 15 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y curl xz-utils tar

      - name: Download Alpine release
        run: |
          VERSION=$(curl -s http://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/$(uname -m)/latest-releases.yaml | grep -m 1 -oP "version: \K.*")
          curl -LO http://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/$(uname -m)/alpine-minirootfs-$VERSION-$(uname -m).tar.gz

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: rootfs.tar.gz
          path: alpine-minirootfs-*.tar.gz
