name: Build Alpine Rootfs

on:
  schedule:
    - cron: "0 0 15 * *"
  workflow_dispatch:

jobs:
  build-alpine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Alpine scripts for debootstrap
        run: |
          sudo apt-get update && sudo apt-get install -y debootstrap wget
          sudo wget -qO /usr/share/debootstrap/scripts/alpine https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.13.0/alpine-chroot-install
          sudo chmod +x /usr/share/debootstrap/scripts/alpine

      - name: Create Rootfs
        run: |
          sudo debootstrap --variant=minbase --components=main --include=ca-certificates,apk-tools,openssh-client stable ./alpine
          sudo chroot ./alpine sh -c "apk add --no-cache bash"
          sudo tar -C ./alpine -czvf rootfs.tar.gz .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITGUB_TOKEN }}
        with:
          tag_name: v$(date +'%Y%m%d')
          release_name: Alpine rootfs release $(date +'%Y%m%d')
          draft: false
          prerelease: false

      - name: Upload Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITGUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rootfs.tar.gz
          asset_name: rootfs.tar.gz
          asset_content_type: application/x-gzip

      - name: Delete Release and Tag
        if: success()
        run: |
          git push --delete origin $(git tag --points-at HEAD)
          git tag --delete $(git tag --points-at HEAD)
          hub release delete $(git describe --tags)
